apiVersion: v1
kind: Service
metadata:
  name: maintenance-api-service
spec:
  selector:
    app: maintenance-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
